_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 40
epoch:
    value: 30
learning_rate:
    value: 0.001
